### ISSUE TITLE
Snapatac make_fragment_file 'Stranded' argument not working

### ISSUE THREAD

**Issue by sdisorbo** [gagneurlab/scooby_reproducibility#1]
Hi there, 

in the load_neurips_into_snapatac.ipynb file, I noticed in the block of code where we make the fragment file with snapatac, the argument 'stranded' isn't a valid argument for the function. 
```

if (len(whitelist) > 0) & (~os.path.exists(os.path.join(out_path, f'{sample}.fragments.bed.minus.gz'))):
        sp.pp.make_fragment_file(
            sample_file,
            output_file=outfile,
            barcode_tag="CB",
            umi_tag="UB",
            umi_regex=None,
            stranded=True,
            is_paired=False,
            shift_left=0,
            shift_right=0
        )
```

I am curious if you ran into this issue/how you were able to create separate strands with this being the case.

**Comment by lauradmartens** [comment]
Hi!

Thanks for your question! It sounds like you may be using the original snapatac package not the adapted one: https://github.com/lauradmartens/SnapATAC2? You can now also just install it using `pip install snapatac2-scooby`. We also provide an example notebook here: https://scooby.readthedocs.io/en/latest/notebooks/data_loading_example.html

Let me know if this solves the issue!
